services:
  lambda-function-url-emulator:
    image: daido1976/aws-lambda-function-url-emulator
    container_name: lambda-function-url-emulator
    ports:
      - "8080:8080"
    environment:
      # Specify the internal port of the lambda rie container
      RIE_ENDPOINT: "http://example-lambda-rie:8080/2015-03-31/functions/function/invocations"
  example-lambda-rie:
    build:
      context: .
    container_name: example-lambda-rie
    ports:
      - "9000:8080"
